name: GitHub Actions OIDC + cosign test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: sigstore/cosign-installer@main
      - uses: imjasonh/setup-ko@v0.4

      - name: Build and sign
        run: |
          IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value')
          COSIGN_EXPERIMENTAL=1 cosign sign \
            --identity-token=${IDTOKEN} \
            $(ko publish ./)

