name: GitHub Actions OIDC + cosign test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: sigstore/cosign-installer@main
      - uses: imjasonh/setup-ko@v0.4
      - name: Build and sign
        run: |
          IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')
          COSIGN_EXPERIMENTAL=1 cosign sign \
            --identity-token=${IDTOKEN} \
            $(ko publish ./)

