name: GitHub Actions OIDC + cosign test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: sigstore/cosign-installer@main
      - uses: imjasonh/setup-ko@v0.4

      - name: Build and sign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign $(ko publish ./)

