name: OIDC Token Test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.1.0'
      - uses: imjasonh/setup-crane@v0.1
      - run: crane copy busybox ghcr.io/imjasonh/ghoidc/image

      - name: Get ID Token
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL
          IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')
          echo $IDTOKEN

          COSIGN_EXPERIMENTAL=1 cosign sign \
            --identity-token=${IDTOKEN} \
            ghcr.io/imjasonh/ghoidc/image

